LLM_PROVIDERS = [
    {"id": "openai", "name": "OpenAI", "base": "https://api.openai.com/v1", "color": "#10A37F", "logo": "/static/logos/openai.png", "mdl": ["gpt-4o", "o3-mini"]},
    {"id": "anthropic", "name": "Anthropic", "base": "https://api.anthropic.com/v1", "color": "#E68D3A", "logo": "/static/logos/anthropic.png", "mdl": ["claude-sonnet-4"]},
    {"id": "google", "name": "Google Gemini", "base": "https://generativelanguage.googleapis.com/v1beta", "color": "#4285F4", "logo": "/static/logos/google.png", "mdl": ["gemini-2.5-pro"]},
    {"id": "deepseek", "name": "DeepSeek", "base": "https://api.deepseek.com/v1", "color": "#4D6BFE", "logo": "/static/logos/deepseek.png", "mdl": ["deepseek-chat"]},
    {"id": "xai", "name": "xAI Grok", "base": "https://api.x.ai/v1", "color": "#E0E0E0", "logo": "/static/logos/xai.png", "mdl": ["grok-4.3"]},
    {"id": "mistral", "name": "Mistral", "base": "https://api.mistral.ai/v1", "color": "#F26522", "logo": "/static/logos/mistral.png", "mdl": ["mistral-large"]},
    {"id": "groq", "name": "Groq", "base": "https://api.groq.com/openai/v1", "color": "#F55036", "logo": "/static/logos/groq.png", "mdl": ["llama-4-scout"]},
    {"id": "cohere", "name": "Cohere", "base": "https://api.cohere.com/v1", "color": "#3953A4", "logo": "/static/logos/cohere.png", "mdl": ["command-r-plus"]},
    {"id": "qwen", "name": "Qwen", "base": "https://dashscope.aliyuncs.com/compatible-mode/v1", "color": "#6A5ACD", "logo": "/static/logos/qwen.png", "mdl": ["qwen-max"]},
    {"id": "kimi", "name": "Kimi", "base": "https://api.moonshot.cn/v1", "color": "#00D4AA", "logo": "/static/logos/kimi.png", "mdl": ["moonshot-v1-8k"]},
    {"id": "glm", "name": "GLM", "base": "https://open.bigmodel.cn/api/paas/v4", "color": "#1677FF", "logo": "/static/logos/glm.png", "mdl": ["glm-4-plus"]},
    {"id": "together", "name": "Together", "base": "https://api.together.xyz/v1", "color": "#0F6FFF", "logo": "/static/logos/together.png", "mdl": ["llama-4-maverick"]},
    {"id": "perplexity", "name": "Perplexity", "base": "https://api.perplexity.ai", "color": "#1DB954", "logo": "/static/logos/perplexity.png", "mdl": ["sonar-pro"]},
    {"id": "silicon", "name": "SiliconFlow", "base": "https://api.siliconflow.cn/v1", "color": "#6366F1", "logo": "/static/logos/silicon.png", "mdl": ["qwen3-235b"]},
    {"id": "yi", "name": "Yi", "base": "https://api.lingyiwanwu.com/v1", "color": "#FF6B6B", "logo": "/static/logos/yi.png", "mdl": ["yi-large"]},
    {"id": "openrouter", "name": "OpenRouter", "base": "https://openrouter.ai/api/v1", "color": "#6366F1", "logo": "/static/logos/custom.svg", "mdl": ["anthropic/claude-sonnet-4", "openai/gpt-4o", "google/gemini-2.5-pro"]},
    {"id": "302ai", "name": "302.ai", "base": "https://api.302.ai/v1", "color": "#FF8C00", "logo": "/static/logos/custom.svg", "mdl": ["gpt-4o", "claude-sonnet-4"]},
    {"id": "custom", "name": "Custom", "base": "", "color": "#888", "logo": "/static/logos/custom.svg", "mdl": []},
]
